const { Client } = require('pg');

const connectionString = "postgres://postgres.xmapjrywkmygxwrctiyi:2580@HoldMyBeer@2580@aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require";

const client = new Client({
  connectionString: connectionString,
  ssl: { rejectUnauthorized: false }
});

async function runSQL() {
  try {
    await client.connect();
    console.log("Connected to Supabase.");

    // Create the table if it doesn't exist
    await client.query(`
      CREATE TABLE IF NOT EXISTS rfid_scans (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          rfid_tag VARCHAR(50) NOT NULL,
          robot_id INT DEFAULT 1,
          status VARCHAR(50) DEFAULT 'scanned',
          scanned_at TIMESTAMP WITH TIME ZONE DEFAULT now()
      );
    `);
    console.log("Table rfid_scans verified/created.");

    // Disable RLS so the Arduino can insert without an authenticated JWT
    await client.query(`
      ALTER TABLE rfid_scans DISABLE ROW LEVEL SECURITY;
    `);
    console.log("Row Level Security disabled for rfid_scans.");

    // Additionally, grant permissions to the 'anon' role so PostgREST allows inserts
    await client.query(`
      GRANT ALL ON TABLE rfid_scans TO anon;
      GRANT ALL ON TABLE rfid_scans TO authenticated;
      GRANT USAGE, SELECT ON SEQUENCE rfid_scans_id_seq TO anon;
      GRANT USAGE, SELECT ON SEQUENCE rfid_scans_id_seq TO authenticated;
    `);
    console.log("Granted permissions to anon role.");

  } catch (err) {
    console.error("Error executing SQL:", err);
  } finally {
    await client.end();
  }
}

runSQL();
